name: Release helm chart
on:
  push:
    branches: [ "main" ]
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-helm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: install helm
        uses: Azure/setup-helm@v3
        with:
          version: 3.11.2

      - name: login to ghcr.io using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/michaelvl/cosign-oci-poc-helm --username ${{ github.repository_owner }} --password-stdin

      - name: save helm chart to local registry
        run: |
          helm package charts/cosign-oci-poc

      - name: publish chart to ghcr.io
        run: |
          helm push cosign-oci-poc-helm-*.tgz oci://ghcr.io/michaelvl | tee helm-push-out.txt
